Ferremas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ferremas_APP.urls')),
]

Ferremas_APP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('construccion/', views.construccion, name='construccion'),
    path('herramientas/', views.herramientas, name='herramientas'),
    path('hogar/', views.hogar, name='hogar'),
    path('piso_y_pared/', views.piso_y_pared, name='piso_y_pared'),
    path('detalle/<int:producto_id>/', views.detalle, name='detalle'), 
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'), 
    path('eliminar_del_carrito/<int:producto_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'), 
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('actualizar_carrito/<int:producto_id>/', views.actualizar_carrito, name='actualizar_carrito'),
    path('carrito/', views.carrito, name='carrito'), 
    path('iniciar_pago/', views.iniciar_pago, name='iniciar_pago'),
    path('webpay_confirmacion/', views.webpay_confirmacion, name='webpay_confirmacion'),
    path('formulario_datos/', views.formulario_datos, name='formulario_datos'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ferremas_APP/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model): # Modelo para los productos
    nombre = models.CharField(max_length=100)  # Campo para el nombre del producto
    descripcion = models.TextField() # Campo para la descripción del producto
    detalleCompleto = models.TextField(default='') # Campo para el detalle completo del producto
    especificaciones = models.CharField(max_length=100, null=True, blank=True) # Campo para las especificaciones del producto
    lista1 = models.CharField(max_length=100, null=True, blank=True) 
    lista2 = models.CharField(max_length=100, null=True, blank=True) 
    lista3 = models.CharField(max_length=100, null=True, blank=True) 
    lista4 = models.CharField(max_length=100, null=True, blank=True)
    lista5 = models.CharField(max_length=100, null=True, blank=True)
    incluye = models.CharField(max_length=100, null=True, blank=True)
    lista6 = models.CharField(max_length=100, null=True, blank=True)
    lista7 = models.CharField(max_length=100, null=True, blank=True)
    lista8 = models.CharField(max_length=100, null=True, blank=True)
    lista9 = models.CharField(max_length=100, null=True, blank=True)
    lista10 = models.CharField(max_length=100, null=True, blank=True)
    precioOferta = models.DecimalField(max_digits=8, decimal_places=2 , null=True, blank=True) # Campo para el precio del producto
    precio = models.DecimalField(max_digits=8, decimal_places=2) # Campo para el precio del producto
    stock = models.IntegerField() # Campo para el stock del producto
    imagen = models.ImageField(upload_to='productos', null=True, blank=True) # Campo para la imagen del producto
    

    def __str__(self):
        return self.nombre
    
class Carrito(models.Model): # Modelo para el carrito de compras
    sesion_id = models.CharField(max_length=100) # Campo para la sesión del carrito

class CarritoProducto(models.Model): # Modelo para los productos del carrito
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE) # Relación con el carrito
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) # Relación con el producto
    cantidad = models.IntegerField() # Campo para la cantidad de productos

class Pedido(models.Model): # Modelo para los pedidos
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # Opcional
    TIPO_ENTREGA_CHOICES = [ # Opciones para el tipo de entrega
        ('RT', 'Retiro en Tienda'), 
        ('DD', 'Despacho a Domicilio')
    ]
     
    tipo_entrega = models.CharField(max_length=2, choices=TIPO_ENTREGA_CHOICES, default='RT') # Campo para el tipo de entrega
    rut = models.CharField(max_length=12) # Campo para el RUT del cliente
    nombre = models.CharField(max_length=100) # Campo para el nombre del cliente
    apellidos = models.CharField(max_length=100) # Campo para los apellidos del cliente
    email = models.EmailField() # Campo para el correo electrónico del cliente
    numero_pedido = models.CharField(max_length=10, unique=True) # Campo para el número de pedido
    datos_completados = models.BooleanField(default=False)  # Nuevo campo para indicar si los datos del cliente han sido completados

    def __str__(self):
        return f'Pedido {self.numero_pedido}'

    def get_nombre_completo(self):
        return f'{self.nombre} {self.apellidos}'

    def get_email(self):
        return self.email
    
class Transaccion(models.Model): # Modelo para las transacciones
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE) # Relación con el pedido
    token = models.CharField(max_length=100) # Campo para el token de la transacción
    buy_order = models.CharField(max_length=100) # Campo para el número de orden de la transacción
    session_id = models.CharField(max_length=100) # Campo para la sesión de la transacción
    amount = models.DecimalField(max_digits=10, decimal_places=2) # Campo para el monto de la transacción
    status = models.CharField(max_length=50) # Campo para el estado de la transacción
    authorization_code = models.CharField(max_length=50, null=True, blank=True) # Campo para el código de autorización
    payment_type_code = models.CharField(max_length=50, null=True, blank=True) # Campo para el código de tipo de pago
    response_code = models.CharField(max_length=50, null=True, blank=True) # Campo para el código de respuesta
    transaction_date = models.DateTimeField(auto_now_add=True) # Campo para la fecha de la transacción

    def __str__(self):
        return f'Transaccion {self.token} - {self.status}'

    def get_cliente_nombre(self):
        return self.pedido.nombre

    def get_cliente_apellidos(self):
        return self.pedido.apellidos

    def get_cliente_email(self):
        return self.pedido.email

    get_cliente_nombre.short_description = 'Nombre'
    get_cliente_apellidos.short_description = 'Apellidos'
    get_cliente_email.short_description = 'Correo Electrónico'

class PerfilUsuario(models.Model): # Modelo para el perfil de usuario
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Relación con el usuario
    rut = models.CharField(max_length=12) # Campo para el RUT del cliente 
    nombre = models.CharField(max_length=100) # Campo para el nombre del cliente
    apellidos = models.CharField(max_length=100) # Campo para los apellidos del cliente
    email = models.EmailField() # Campo para el correo electrónico del cliente

    def __str__(self):
        return f'Perfil de {self.user.username}'

Ferremas_APP/views.py
from django.shortcuts import get_object_or_404, render, redirect
from Ferremas_APP.templatetags.custom_filters import formato_moneda
from .models import Producto, Carrito, CarritoProducto, Pedido, Transaccion, PerfilUsuario
from django.http import JsonResponse
from django.views.decorators.http import require_POST
import json
from decimal import Decimal
from django.urls import reverse
from transbank.webpay.webpay_plus.transaction import Transaction, WebpayOptions
from django.conf import settings
from transbank.error.transbank_error import TransbankError
import random
from .forms import PedidoForm, RegistroUsuarioForm
from .utils import enviar_correo_confirmacion, obtener_tipo_cambio, SERIES_CODIGOS
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError, transaction
import logging

logger = logging.getLogger(__name__)


def index(request): # Vista para la página de inicio
    productos = Producto.objects.all() # Se obtienen todos los productos
    return render(request, 'pages/home/index.html', {'productos': productos}) # Se renderiza la plantilla con los productos

@require_POST # Solo se aceptan peticiones POST
def agregar_al_carrito(request, producto_id): # Vista para agregar un producto al carrito
    if request.method == 'POST': # Si la petición es POST
        csrf_token = request.POST.get('csrfmiddlewaretoken') # Se obtiene el token CSRF
        if not csrf_token: # Si no se encuentra el token CSRF
            return JsonResponse({'mensaje': "CSRF token no encontrado."}, status=403) # Se responde con un mensaje de error
        
        carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión
        if not carrito_id: # Si no existe un carrito en la sesión
            nuevo_carrito = Carrito.objects.create() # Se crea un nuevo carrito
            request.session["carrito_id"] = nuevo_carrito.id # Se guarda el id del carrito en la sesión
        else: # Si existe un carrito en la sesión
            nuevo_carrito = Carrito.objects.get(id=carrito_id) # Se obtiene el carrito
        
        producto = get_object_or_404(Producto, pk=producto_id) # Se obtiene el producto
        if producto.stock > 0: # Si el producto tiene stock
            carrito_producto, created = CarritoProducto.objects.get_or_create( # Se obtiene o crea un CarritoProducto
                carrito=nuevo_carrito, # Se asigna el carrito
                producto=producto, # Se asigna el producto
                defaults={'cantidad': 1} # Se asigna la cantidad inicial
            )
            if not created: # Si el CarritoProducto ya existe
                if carrito_producto.cantidad < producto.stock: # Si la cantidad es menor al stock
                    carrito_producto.cantidad += 1 # Se aumenta la cantidad
                    carrito_producto.save() # Se guarda el CarritoProducto
            return JsonResponse({'mensaje': "Producto agregado al carrito"}) # Se responde con un mensaje
        else: # Si el producto no tiene stock
            return JsonResponse({'mensaje': "Producto sin stock"}, status=400) # Se responde con un mensaje de error

    
def ver_carrito(request): # Vista para ver el contenido del carrito
    carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión
    if carrito_id: # Si existe un carrito en la sesión
        carrito = Carrito.objects.get(id=carrito_id) # Se obtiene el carrito
        productos_en_carrito = CarritoProducto.objects.filter(carrito=carrito) # Se obtienen los productos del carrito
        productos = [ # Se crea una lista con los productos del carrito
            {'id': cp.producto.id, 'nombre': cp.producto.nombre, 'cantidad': cp.cantidad, 'precio': cp.producto.precioOferta} # Se crea un diccionario con los datos del producto
            for cp in productos_en_carrito # Se recorren los productos del carrito
        ]
        total = sum(cp.cantidad * cp.producto.precioOferta for cp in productos_en_carrito) # Se calcula el total del carrito
        return JsonResponse({'productos': productos, 'total': float(total)}) # Se responde con los productos y el total
    else: # Si no existe un carrito en la sesión
        return JsonResponse({'productos': [], 'total': 0.0}) # Se responde con una lista vacía y total 0.0

@require_POST # Solo se aceptan peticiones POST
def actualizar_carrito(request, producto_id): # Vista para actualizar la cantidad de un producto en el carrito
    try: # Se intenta realizar la operación
        data = json.loads(request.body) # Se obtiene la información del cuerpo de la petición
        cantidad = int(data.get('cantidad', 0)) # Se obtiene la cantidad del producto
        carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión

        if carrito_id: # Si existe un carrito en la sesión
            carrito_producto = get_object_or_404(CarritoProducto, carrito_id=carrito_id, producto_id=producto_id) # Se obtiene el CarritoProducto
            if cantidad > 0 and cantidad <= carrito_producto.producto.stock: # Si la cantidad es mayor a 0 y menor o igual al stock
                carrito_producto.cantidad = cantidad # Se actualiza la cantidad
                carrito_producto.save() # Se guarda el CarritoProducto
            elif cantidad == 0: # Si la cantidad es 0
                carrito_producto.delete() # Se elimina el CarritoProducto
            # Calcular el total del carrito después de actualizar
            productos_en_carrito = CarritoProducto.objects.filter(carrito_id=carrito_id) # Se obtienen los productos del carrito
            total_carrito = sum(item.cantidad * item.producto.precioOferta for item in productos_en_carrito) # Se calcula el total del carrito
            return JsonResponse({'mensaje': 'Cantidad actualizada correctamente', 'totalCarrito': float(total_carrito)}) # Se responde con un mensaje y el total del carrito
        return JsonResponse({'mensaje': 'Error al actualizar el carrito'}, status=400) # Si no existe un carrito en la sesión, se responde con un mensaje de error
    except Exception as e: # Si ocurre un error
        return JsonResponse({'mensaje': str(e)}, status=500) # Se responde con un mensaje de error


@require_POST # Solo se aceptan peticiones POST
def eliminar_del_carrito(request, producto_id): # Vista para eliminar un producto del carrito
    carrito_id = request.session.get("carrito_id") # Se obtiene el id del carrito de la sesión
    if not carrito_id: # Si no existe un carrito en la sesión
        return JsonResponse({'mensaje': "No existe el carrito"}, status=404) # Se responde con un mensaje de error

    try: # Se intenta realizar la operación
        carrito_producto = CarritoProducto.objects.get(carrito_id=carrito_id, producto_id=producto_id) # Se obtiene el CarritoProducto
        carrito_producto.delete() # Se elimina el CarritoProducto
        return JsonResponse({'mensaje': 'Producto eliminado del carrito'}) # Se responde con un mensaje
    except CarritoProducto.DoesNotExist: # Si el CarritoProducto no existe
        return JsonResponse({'mensaje': 'Producto no encontrado en el carrito'}, status=404) # Se responde con un mensaje de error

def construccion(request): 
    return render(request, 'pages/home/construccion.html')

def herramientas(request):
    return render(request, 'pages/home/herramientas.html')

def hogar(request):
    return render(request, 'pages/home/hogar.html')

def piso_y_pared(request):
    return render(request, 'pages/home/piso-y-pared.html')

def registro(request): # Vista para el registro de usuarios
    if request.method == 'POST':   # Si la petición es POST
        form = RegistroUsuarioForm(request.POST) # Se crea un formulario de registro con los datos de la petición
        if form.is_valid(): # Si el formulario es válido
            try:   # Se intenta guardar el usuario
                with transaction.atomic(): # Se inicia una transacción
                    user = form.save() # Se guarda el usuario
                    login(request, user) # Se inicia sesión con el usuario
                    if request.headers.get('x-requested-with') == 'XMLHttpRequest': # Si la petición es una petición AJAX
                        return JsonResponse({'success': True}) # Se responde con un mensaje de éxito
                    else: # Si la petición no es una petición AJAX
                        return redirect('formulario_datos') # Se redirige al formulario de datos
            except IntegrityError as e: # Si ocurre un error de integridad
                form.add_error(None, 'Error al guardar el usuario. Por favor, intente de nuevo.') # Se agrega un error al formulario
                if request.headers.get('x-requested-with') == 'XMLHttpRequest': # Si la petición es una petición AJAX
                    errors = {field: [str(error) for error in error_list] for field, error_list in form.errors.items()} # Se obtienen los errores del formulario
                    return JsonResponse({'success': False, 'errors': errors}) # Se responde con un mensaje de error
                else:
                    return render(request, 'pages/registration/registro.html', {'form': form, 'errors': form.errors}) # Se renderiza la plantilla con el formulario y los errores
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest': # Si la petición es una petición AJAX
                errors = {field: [str(error) for error in error_list] for field, error_list in form.errors.items()} # Se obtienen los errores del formulario
                return JsonResponse({'success': False, 'errors': errors}) # Se responde con un mensaje de error
            else:
                return render(request, 'pages/registration/registro.html', {'form': form, 'errors': form.errors}) 
    else:
        form = RegistroUsuarioForm() # Se crea un formulario de registro

Ferremas_APP/templates/pages/cart/carrito.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}

{% block contenido %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 1000px;">
    <div class="bg-secondary bg-opacity-10 p-5 rounded-5">
        <div class="mb-5">
            <h1 class="text-center mb-4" style="font-size: 3.6rem; font-weight: bold; text-transform: uppercase;">Carrito de Compras</h1>
        </div>
        <div class="table-responsive" style="max-height: 550px; max-width: 1100px;">
            <table class="table table-bordered" >
                <thead class="table-success">
                    <tr>
                        <th scope="col" class="px-5 py-4">Imagen</th>
                        <th scope="col" class="px-5 py-4">Nombre</th>
                        <th scope="col" class="px-5 py-4">Descripción</th>
                        <th scope="col" class="px-5 py-4">Detalle Completo</th>
                        <th scope="col" class="px-5 py-4">Cantidad</th>
                        <th scope="col" class="px-3 py-4">Precio Unitario</th>
                        <th scope="col" class="px-5 py-4">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td class="px-5 py-5"><img src="{{ producto.imagen }}" alt="{{ producto.nombre }}" class="p-2 rounded-3 border border-2 border-dark-subtle" style="max-width: 150px;"></td>
                        <td class="px-5 py-5">{{ producto.nombre }}</td>
                        <td class="px-5 py-5">{{ producto.descripcion }}</td>
                        <td class="px-5 py-5">{{ producto.detalleCompleto|truncatechars:80 }}</td>
                        <td class="px-5 py-5">{{ producto.cantidad }}</td>
                        <td class="px-5 py-5">{{ producto.precio|formato_moneda }}</td>
                        <td class="px-5 py-5">{{ producto.total|formato_moneda }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="text-end mt-5">
            <p class="fs-3" style="font-weight: bold; text-transform: uppercase;">Subtotal: {{ total|formato_moneda }}</p>
            <p class="fs-3" style="font-weight: bold; text-transform: uppercase;">IVA (19%): {{ iva|formato_moneda }}</p>
            <h4 class="fs-1" style="font-weight: bold; text-transform: uppercase;">Total: {{ total_con_iva|formato_moneda }}</h4>
            <div class="d-flex justify-content-between">
                <div>
                    <a href="{% url 'formulario_datos' %}" class="btn btn-warning fs-2 btn-lg mt-5 px-5">Modificar datos cliente</a>
                </div>
                <form action="{% url 'iniciar_pago' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="total_con_iva" value="{{ total_con_iva|floatformat:0 }}">
                    <button type="submit" class="btn btn-success fs-2 btn-lg mt-5 px-5">Pagar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ferremas_APP/templates/pages/cart/correo_confirmacion.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Ubuntu', sans-serif;
            font-size: 1.8rem;
            font-weight: 300;
            color: #000000;}
    </style>
</head>
<body>
    <h1 style="font-size: 2.4rem; font-weight: 700; margin-bottom: 80; margin-top: 80px;">Confirmación de Pedido</h1>
    <p class="mt-5 mb-0" >Estimado/a {{ perfil.nombre }} {{ perfil.apellidos }},</p>
    <p>Su pedido ha sido confirmado con los siguientes detalles:</p>
    <h2 class="mb-5" style="font-size: 1.8rem; font-weight: 700;">Detalles del Pedido</h2>
    <ul class="mb-5" style="list-style: none;">
        <li><strong>Número de Pedido:</strong> {{ pedido.numero_pedido }}</li>
        <li><strong>RUT:</strong> {{ perfil.rut }}</li>
        <li><strong>Nombre:</strong> {{ perfil.nombre }}</li>
        <li><strong>Apellidos:</strong> {{ perfil.apellidos }}</li>
        <li><strong>Correo Electrónico:</strong> {{ perfil.email }}</li>
    </ul>
    <h2 class="mb-5" style="font-size: 1.8rem; font-weight: 700;">Detalles de la Transacción</h2>
    <ul class="mb-5" style="list-style: none;">
        <li><strong>Token:</strong> {{ transaccion.token }}</li>
        <li><strong>Monto:</strong> ${{ transaccion.amount }}</li>
        <li><strong>Código de Autorización:</strong> {{ transaccion.authorization_code }}</li>
    </ul>
    <h1>Gracias por su compra.</h1>
</body>
</html>

Ferremas_APP/templates/pages/cart/formulario_datos.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
<div style="height: 910px;">
    <div class="container bg-secondary bg-opacity-10 rounded-5 pt-5" style="height: 800px; width: 600px; margin-top: 80px;">
        <div class="row mt-5 mb-5 text-uppercase">
            <div class="col text-center mb-5">
                <h1 class="fw-bold" style="font-size: 3.6rem;">Datos del Cliente</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form id="datos-cliente-form" class="formulario-retiro-entrega" method="post" action="">
                    {% csrf_token %}
                    <div class=" mb-5">
                        <label for="id_tipo_entrega" class="form-label mb-5 fs-2">Seleccione el tipo de entrega</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="tipo_entrega" id="tipo_entrega_rt" value="RT" checked>
                            <label class="form-check-label" for="tipo_entrega_rt">Retiro en Tienda</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="tipo_entrega" id="tipo_entrega_dd" value="DD" disabled>
                            <label class="form-check-label" for="tipo_entrega_dd">Despacho a Domicilio (Próximamente)</label>
                        </div>
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_rut" class="form-label input-retiro-entrega">Rut</label>
                        {{ form.rut }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_nombre" class="form-label">Nombre</label>
                        {{ form.nombre }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_apellidos" class="form-label">Apellidos</label>
                        {{ form.apellidos }}
                    </div>
                    <div class="mb-3 fs-3">
                        <label for="id_email" class="form-label">Correo Electrónico</label>
                        {{ form.email }}
                    </div>
                    <div class="d-flex justify-content-between mt-5">
                        <button type="submit" class="btn btn-success fs-2 btn-lg px-5">Ir al Carrito</button>
                        <a href="{% url 'index' %}" class="btn btn-secondary fs-2 btn-lg px-5">Ir al Home</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const rutInput = document.getElementById('id_rut');
        
        rutInput.addEventListener('input', formatRUT);
        
        function formatRUT() {
            let value = rutInput.value.replace(/\./g, '').replace(/-/g, '');
            if (value.length > 1) {
                value = value.slice(0, -1).replace(/\B(?=(\d{3})+(?!\d))/g, '.') + '-' + value.slice(-1);
            }
            rutInput.value = value;
        }
    
        function verificarCarrito() {
            fetch("/ver_carrito/")
                .then(response => response.json())
                .then(data => {
                    const irCarritoBtn = document.querySelector('button[type="submit"]');
                    if (data.productos.length === 0) {
                        irCarritoBtn.disabled = true;
                        Swal.fire({
                            icon: 'error',
                            title: 'Carrito vacío',
                            text: 'No hay productos en el carrito. Por favor, agrega productos antes de proceder.',
                            confirmButtonText: 'Aceptar'
                        });
                    } else {
                        irCarritoBtn.disabled = false;
                    }
                })
                .catch(error => console.error("Error al verificar el carrito:", error));
        }
    
        verificarCarrito(); // Llamar a la función al cargar la página
    });
    </script>
    

{% endblock %}

Ferremas_APP/templates/pages/cart/pago_exitoso.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container-fuid d-flex justify-content-center align-items-center" style="height: 100vh">
    <div class="container d-flex justify-content-center bg-success-subtle rounded-5 w-25" style="height: 600px; margin-top: 80px; margin-bottom: 80px;">
        <div class="d-flex flex-column align-items-center justify-content-center ">
            <div class="justify-content-center align-items-center">
                <h1 class="mb-5" style="font-size: 3.2rem; font-weight: bold;">Pago Exitoso</h1>
            </div>
            <div class="justify-content-center align-items-center">
                <p class="fs-2 mb-5">Tu pago ha sido procesado exitosamente.</p>
                <p class="fs-2">Detalles del pedido.</p>
                <ul class="fs-2" style="list-style: none;">
                    <li><strong>Número de Pedido: </strong>{{ pedido.numero_pedido }}</li>
                    <li><strong>RUT: </strong>{{ pedido.rut }}</li>
                    <li><strong>Nombre: </strong>{{ pedido.nombre }}</li>
                    <li><strong>Apellidos: </strong>{{ pedido.apellidos }}</li>
                    <li><strong>Correo Electrónico: </strong>{{ pedido.email }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ferremas_APP/templates/pages/cart/pago_fallido.html
{% extends 'base.html' %}

{% block contenido %}
<div class="container-fuid d-flex justify-content-center align-items-center" style="height: 800px">
    <div class="container d-flex justify-content-center bg-success-subtle rounded-5 w-50" style="height: 450px; margin-top: 20px; margin-bottom: 20px;">
        <div class="d-flex flex-column align-items-center justify-content-center px-5">
            <div class="justify-content-center align-items-center">
                <h1 class="mb-5" style="font-size: 3.2rem; font-weight: bold;">Pago Fallido</h1>
            </div>
            <div class="justify-content-center align-items-center">
                <p class="fs-2 mb-5">Hubo un problema al procesar tu pago. Por favor, intenta nuevamente.</p>
                <p class="fs-2">Detalles del pedido.</p>
                <ul class="fs-2 ms-0" style="list-style: none;">
                    <li class="ms-0">El Banco emisor impidió la transacción sin una razón en específica. <strong>Código: -1</strong></li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}